name: image_cropper_view
description: A widget to crop your images. It supports pan, zoom, rotate gestures.
version: 0.0.2
homepage: https://github.com/gliheng/image_cropper_view

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
